package sqlxgen

import (
	"io"
	"text/template"
)

const tmplStr = `// Code generated by sqlx-gen. DO NOT EDIT.

package {{ .PackageName }}
{{ range .Tables }}
type {{ .Name }} struct {
{{- range .Columns }}
	{{ .GoName }} {{ .Type }} {{ .StructTag }}
{{- end }}
}
{{ end }}`

var tmpl = template.Must(template.New("sqlxgen").Parse(tmplStr))

type Info struct {
	PackageName string
	Tables      []*Table
}

func Generate(w io.Writer, info *Info) error {
	return tmpl.Execute(w, info)
}
